POST   http://localhost:3333/courses
Content-Type:  application/json

{
    "title" : "zod confi"
}

###

GET    http://localhost:3333/courses?orderBy=title&page=3

###

GET http://localhost:3333/courses/f94abb18-dcd4-4b51-ba71-6f87f735a906


###

DELETE http://localhost:3333/courses/1

###

PATCH http://localhost:3333/courses/1
Content-Type:  application/json

{
    "title" : "Teste titulo"
}
