POST   http://localhost:3333/courses
Content-Type:  application/json

{
    "title" : "Teste titulo"
}

###

GET    http://localhost:3333/courses

###

GET http://localhost:3333/courses/3


###

DELETE http://localhost:3333/courses/1

###

PATCH http://localhost:3333/courses/1
Content-Type:  application/json

{
    "title" : "Teste titulo"
}
